name: 'Build bleeding edge'

on:
  push:
    branches: master

jobs:
  build:
    name: 'Build linux'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
#      - name: get VCV Rack 1.1.5 SDK
#        run: wget https://vcvrack.com/downloads/Rack-SDK-1.1.5.zip -P ./sdk -O temp.zip; unzip ./sdk/temp.zip; rm sdk./temp.zip
#      - name: configure
#        run: ./configure
#      - name: make
#        run: make
#      - name: make check
#        run: make check
#      - name: make distcheck
#        run: make distcheck
